name: Generate Release with All Files

on:
  push:
    branches:
      - output

jobs:
  generate-release:
    name: Generate Release with All Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git user for tagging
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create Tag
        run: git tag latest ${{ github.sha }}
        if: success()

      - name: Push Tag
        uses: ad-m/github-push-action@master
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: latest

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload All Files
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./data.json
          asset_name: all_files.zip  # Name of the release asset
          asset_content_type: application/zip
